# Disable sudo to speed up the build
sudo: false

language: python
python:
  - "3.7"
  - "3.8"

# Install the codecov pip dependency
install:
  - pip install codecov
  - pip install pytest
  - pip install pytest-cov
  - pip install -r requirements.txt

# command to run tests
script:
  - "pytest --cov-report=xml --cov=ode_composer tests/ "

# Push the results back to codecov
after_success:
  - codecov
